name: Build & Release

on:
    - push

jobs:
    build-test:
        name: Build & Test
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use node
              uses: actions/setup-node@v4.0.3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build

    release:
        name: Release
        runs-on: ubuntu-24.04
        needs: build-test
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use node
              uses: actions/setup-node@v4.0.3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci
            - name: Release
              run: npm run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
